"""Guards the Alembic migrations against drift from the models.

Not in the spec's test list, but justified: the rest of the suite builds its
schema with `Base.metadata.create_all`, so a migration that is missing, broken,
or out of date would never be exercised — and would only be discovered on a
real deployment. These two tests close that gap:

1. `alembic upgrade head` actually runs (catches syntax/NameError bugs in a
   migration, which autogenerated files are prone to).
2. The resulting schema matches the models exactly (catches a model change
   committed without a migration).
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic import command
from alembic.autogenerate import compare_metadata
from alembic.config import Config
from alembic.migration import MigrationContext
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.exc import IntegrityError

from app.core.database import Base

BACKEND_DIR = Path(__file__).resolve().parents[1]
EXPECTED_TABLES = {"products", "sales_history", "suppliers", "orders", "audit_log"}


@pytest.fixture
def migrated_url(tmp_path: Path) -> str:
    """Run migrations to head against a throwaway file database."""
    db_path = (tmp_path / "migrated.db").as_posix()
    url = f"sqlite:///{db_path}"

    config = Config(str(BACKEND_DIR / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    config.set_main_option("sqlalchemy.url", url)
    command.upgrade(config, "head")

    return url


def test_migrations_run_and_create_every_table(migrated_url: str) -> None:
    engine = create_engine(migrated_url)
    try:
        tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    assert EXPECTED_TABLES <= tables
    assert "alembic_version" in tables


def test_migrated_schema_matches_the_models(migrated_url: str) -> None:
    """A model change without a matching migration fails here."""
    engine = create_engine(migrated_url)
    try:
        with engine.connect() as connection:
            context = MigrationContext.configure(
                connection,
                opts={
                    "compare_type": True,
                    "target_metadata": Base.metadata,
                    "render_as_batch": True,
                },
            )
            diff = compare_metadata(context, Base.metadata)
    finally:
        engine.dispose()

    assert diff == [], f"Models and migrations have diverged: {diff}"


def test_timestamp_columns_survive_a_round_trip_as_utc(db) -> None:
    """Regression guard for the SQLite tzinfo-dropping bug.

    Before UTCDateTime existed, SQLite returned naive datetimes here and the API
    serialised timestamps with no UTC offset.
    """
    from datetime import timezone

    from app.models.product import Product

    product = Product(name="Milk", unit="litre", current_stock=1, reorder_threshold=2)
    db.add(product)
    db.commit()

    # Force a real read from the database rather than the identity map.
    db.expire_all()
    reloaded = db.get(Product, product.id)
    assert reloaded is not None

    assert reloaded.created_at.tzinfo is not None
    assert reloaded.created_at.utcoffset() == timezone.utc.utcoffset(None)


# --- enum CHECK constraints -------------------------------------------------
#
# These exist because Alembic autogenerate does not compare CHECK constraints.
# `test_migrated_schema_matches_the_models` uses `compare_metadata`, which is
# blind to them — so a missing constraint would pass every other test in the
# suite while leaving the column a bare VARCHAR. (That was in fact the state
# until revision dfe80c1e476d: `Enum(native_enum=False)` defaults to
# `create_constraint=False`.)


@pytest.mark.parametrize(
    "table,column,constraint,bad_value",
    [
        ("orders", "status", "ck_orders_order_status", "definitely_paid"),
        ("audit_log", "actor", "ck_audit_log_audit_actor", "hacker"),
        (
            "webhook_events",
            "outcome",
            "ck_webhook_events_webhook_outcome",
            "whatever",
        ),
    ],
)
def test_enum_columns_have_an_enforced_check_constraint(
    migrated_url: str, table: str, column: str, constraint: str, bad_value: str
) -> None:
    """A bogus value must be refused by the database, not just by Python."""
    engine = create_engine(migrated_url)
    try:
        with engine.connect() as connection:
            ddl = connection.execute(
                text("SELECT sql FROM sqlite_master WHERE name = :name"),
                {"name": table},
            ).scalar()
            assert constraint in (ddl or ""), (
                f"{table}.{column} has no {constraint}; the column is a bare "
                f"VARCHAR and any string could be stored in it."
            )
    finally:
        engine.dispose()


def test_rejected_is_an_accepted_order_status(migrated_url: str) -> None:
    """The sixth status must be permitted by the constraint, not just the enum."""
    engine = create_engine(migrated_url)
    try:
        with engine.connect() as connection:
            ddl = connection.execute(
                text("SELECT sql FROM sqlite_master WHERE name = 'orders'")
            ).scalar()
        assert "'rejected'" in ddl
        for status in ("proposed", "approved", "paid", "failed", "reversed"):
            assert f"'{status}'" in ddl
    finally:
        engine.dispose()


def test_invalid_status_is_rejected_by_the_database(migrated_url: str) -> None:
    """End-to-end proof, bypassing the ORM entirely."""
    engine = create_engine(migrated_url)
    try:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "INSERT INTO products (name, current_stock, unit, "
                    "reorder_threshold, created_at, updated_at) "
                    "VALUES ('P', 1, 'u', 1, '2026-01-01', '2026-01-01')"
                )
            )
            connection.execute(
                text(
                    "INSERT INTO suppliers (product_id, name, "
                    "price_per_unit_paise, delivery_days, created_at, updated_at) "
                    "VALUES (1, 'S', 100, 1, '2026-01-01', '2026-01-01')"
                )
            )

        with pytest.raises(IntegrityError):
            with engine.begin() as connection:
                connection.execute(
                    text(
                        "INSERT INTO orders (product_id, supplier_id, quantity, "
                        "amount_paise, status, created_at, updated_at) "
                        "VALUES (1, 1, 1, 100, 'totally_paid_trust_me', "
                        "'2026-01-01', '2026-01-01')"
                    )
                )
    finally:
        engine.dispose()
